orbitdotnet:
  - '**/Dotnet.Results/**/*'  # Arquivos que acionam o r칩tulo dotnet.TestApp

orbitdotnetresult:
  - '**/Dotnet.TestApp/**/*'  # Arquivos que acionam o r칩tulo dotnet.Results

documentation:
  - '**/*.md'  # Qualquer arquivo Markdown que acionar치 o r칩tulo documentation
