OrbitDotnet:
- changed-files:
  - any-glob-to-any-file: 'Dotnet.TestApp/**/*'

OrbitDotnet.Results:
- changed-files:
  - all-globs-to-all-files: ['!Dotnet.Results/*.md', '!Dotnet.Results/docs/*']
  

documentation:
- changed-files:
  - any-glob-to-any-file:
    - '*.md'
    - '.github/**/*.md'
    - 'Dotnet.Results/docs/**/*'
    - 'Dotnet.Results/README.md'
