OrbitDotnet:
- changed-files:
  - any-glob-to-any-file: 'Dotnet.TestApp/**/*'

OrbitDotnet.Results:
- changed-files:
  - any-glob-to-any-file: 'Dotnet.Results/**/*'
  - all-globs-to-all-files: '!Dotnet.Results/docs/*'
  - all-globs-to-all-files: '!Dotnet.Results/*.md'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - '*.md'
    - '.github/**/*.md'
    - 'Dotnet.Results/docs/**/*'
    - 'Dotnet.Results/README.md'
