OrbitDotnet:
- changed-files:
  - any-glob-to-any-file: 'Dotnet.TestApp/**/*'

OrbitDotnet.Results:
- changed-files:
  - any-glob-to-any-file: ['Dotnet.Results/**/*', '!Dotnet.Results/docs/**/*', '!Dotnet.Results/README.md']

documentation:
- changed-files:
  - any-glob-to-any-file:
    - '*.md'
    - '.github/**/*.md'
