name: CI

on:
  pull_request:
    types: [closed]

jobs:
    build:
        if: ${{ contains(github.event.pull_request.labels.*.name, 'Dotnet.Results') }}
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
        - name: Run a one-line script
          run: echo Hello, ${{ github.event.label.name }}
