name: Detect Changes

on:
  workflow_call:

jobs:
  label-pr:
    runs-on: ubuntu-latest
    name: Detect changed files
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}  # Armazena os arquivos alterados no output
    steps:
    - uses: actions/checkout@v4  # Faz o checkout do repositório

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45  # Usa a ação para obter os arquivos alterados

    - name: Set output for changed files
      run: echo "changed_files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT  # Define o output
