name: Echo test

on:
    workflow_call: 
        inputs:
            FILES_CHANGED:
                type: string
                required: true
                default: ""

jobs:
    echo:
        name: Echo files changed
        runs-on: ubuntu-latest

        steps:
        - name: Run echo command
          run: echo ${{ inputs.FILES_CHANGED }}
