name: (Internal) Handle PR Labels based in a commit
run-name:  (Internal) Handle PR Labels based in a commit

on:
  workflow_call:
    outputs:
      ORBITDOTNET_FOUND:
        value: ${{ jobs.get_labels_release.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND:
        value: ${{ jobs.get_labels_release.outputs.ORBITDOTNET_RESULTS_FOUND }}
        
jobs:
  get_labels_release:
    runs-on: ubuntu-latest
    outputs:
      ORBITDOTNET_FOUND: ${{ steps.get_labels_release.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND: ${{ steps.get_labels_release.outputs.ORBITDOTNET_RESULTS_FOUND }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --hostname atc-github.azure.cloud.bmw --with-token
        
      - name: Get the latest commit SHA
        id: get_labels_release
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          pr=$(gh pr list --search "${{ env.COMMIT_SHA }}" --json number --jq '.[0].number')
          echo "$pr"
 
          if [ -z "$pr" ]; then
            echo "No PR found for commit ${{ env.COMMIT_SHA }}"
          else
            echo "PR Number: $pr"
            pr_view=$(gh pr view $pr --json labels)

            if echo "$pr_view" | grep -q "OrbitDotnet"; then
              echo "The label 'OrbitDotnet' was found."
              echo "ORBITDOTNET_FOUND=true" >> $GITHUB_OUTPUT
            else
              echo "The label 'orbitdotnet' was not found."
              echo "ORBITDOTNET_FOUND=false" >> $GITHUB_OUTPUT
            fi

            if echo "$pr_view" | grep -q "OrbitDotnet.Results"; then
              echo "The label 'OrbitDotnet.Results' was found."
              echo "ORBITDOTNET_RESULTS_FOUND=true" >> $GITHUB_OUTPUT
            else
              echo "The label 'OrbitDotnet.Results' was not found."
              echo "ORBITDOTNET_RESULTS_FOUND=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Find Pull Request associated with the commit
        id: find_pr
        run: |
          pr=$(gh pr list --search "${{ env.COMMIT_SHA }}" --json number --jq '.[0].number')
          if [ -z "$pr" ]; then
            echo "No PR found for commit ${{ env.COMMIT_SHA }}"
          else
            echo "PR Number: $pr"
            echo "PR_NUMBER=$pr" >> $GITHUB_ENV  # Salvar o número do PR como uma variável de ambiente
          fi

      - name: Output PR Number
        run: |
          echo "The associated PR number is ${{ env.PR_NUMBER }}"
          # run: |
          #   # Obter o commit SHA do push
          #   commit_sha="${{ github.sha }}"
          
        #   # Usar a API do GitHub para encontrar o PR associado ao commit
        #   pr_response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        #     "https://api.github.com/repos/${{ secrets.GITHUB_TOKEN }}/commits/${commit_sha}/pulls")

        #   echo "$pr_response"

        #   # Verificar se o PR foi encontrado
        #   if [[ $(echo "$pr_response" | jq 'length') -gt 0 ]]; then
        #     pr_url=$(echo "$pr_response" | jq -r '.[0].url')

        #     labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$pr_url")

        #     if echo "$labels" | grep -F 'OrbitDotnet",'; then
        #         echo "The label 'OrbitDotnet' was found."
        #         echo "ORBITDOTNET_FOUND=true" >> $GITHUB_OUTPUT