name: Release Candidate Workflow

on:
    pull_request: 
        types: [labeled, closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  
jobs:

    labeled:
        uses: ./.github/workflows/test_labels.yml
