name: Release Candidate Workflow

on:
    pull_request: 
        types: [labeled, closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  
jobs:
    handle_label:
      runs-on: ubuntu-latest
      outputs:
        ORBITDOTNET_FOUND: ${{ steps.handle_label.outputs.ORBITDOTNET_FOUND }}
        RESULTS_FOUND: ${{ steps.handle_label.outputs.RESULTS_FOUND }}
      steps:
        - name: Check PR Labels
          id: handle_label
          run: |
            labels="${{ toJSON(github.event.pull_request.labels) }}"
            echo "Rótulos: $labels"

            if echo "$labels" | grep -q orbitdotnet; then
              echo "O rótulo 'orbitdotnet' está presente."
              echo "ORBITDOTNET_FOUND=true" >> $GITHUB_OUTPUT
              echo $ORBITDOTNET_FOUND
            else
              echo "O rótulo 'orbitdotnet' NÃO está presente."
              echo "ORBITDOTNET_FOUND=false" >> $GITHUB_OUTPUT
            fi

            if echo "$labels" | grep -q results; then
              echo "O rótulo 'results' está presente."
              echo "RESULTS_FOUND=true" >> $GITHUB_OUTPUT
              echo $RESULTS_FOUND
            else
              echo "O rótulo 'results' NÃO está presente."
              echo "RESULTS_FOUND=false" >> $GITHUB_OUTPUT
            fi

    teste:
        needs: handle_label
        runs-on: ubuntu-latest
        steps:
          
          - name: Update package OrbitDotnet
            env:
              ORBITDOTNET_FOUND: ${{needs.handle_label.outputs.ORBITDOTNET_FOUND}}
              RESULTS_FOUND: ${{needs.handle_label.outputs.RESULTS_FOUND}}
            if: env.OUTPUT1 == 'true'
            run: |
              echo "OrbitDotnet = true"


    check-labels:
        needs: handle_label
        runs-on: ubuntu-latest
        steps:
          - name: Get Labels Output
            run: |
              if [ "$ORBITDOTNET_FOUND" = "true" ]; then
                echo "Ações a serem executadas quando o rótulo é encontrado."
              else
                echo "Ações alternativas quando o rótulo não é encontrado."
              fi

              if [ "$RESULTS_FOUND" = "true" ]; then
                echo "Ações a serem executadas quando o rótulo é encontrado."
              else
                echo "Ações alternativas quando o rótulo não é encontrado."
              fi


