name: Release Candidate Workflow

on:
    pull_request: 
        types: [labeled, closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  
jobs:
    call_handle_label:
      uses: ./.github/workflows/handle-label.yml
      with:
        labels: ${{ toJSON(github.event.pull_request.labels) }}


    teste:
        needs: call_handle_label
        runs-on: ubuntu-latest
        steps:
          
          - name: Update package OrbitDotnet
            env:
              ORBITDOTNET_FOUND: ${{needs.handle_label.outputs.ORBITDOTNET_FOUND}}
              RESULTS_FOUND: ${{needs.handle_label.outputs.RESULTS_FOUND}}
            if: env.ORBITDOTNET_FOUND == 'true'
            run: |
              echo "OrbitDotnet = true"

