name: Release Candidate Workflow

on:
    pull_request: 
        types: [labeled, closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  
jobs:

    handle_label:
      runs-on: ubuntu-latest
      steps:
        - name: Check PR Labels
          id: set_output
          run: |
              RAW_LABELS="${{ toJSON(github.event.pull_request.labels) }}"
              echo "Raw PR labels: $RAW_LABELS"
            
              # Extrair os valores da propriedade name
              names=$(echo "$RAW_LABELS" | grep '"name"' | sed -E 's/.*name: ([^,]*).*/\1/')
                                                         
              
              # Exibir os nomes extraídos
              echo "Extracted names:"
              echo "$names"
            

    check-labels:
        needs: handle_label
        runs-on: ubuntu-latest
        steps:
          - name: Get Labels Output
            run: |
                echo "Labels from the labeled job: " echo output.txt
