name: Release Candidate Workflow

on:
    pull_request: 
        types: [labeled, closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  
jobs:

    handle_label:
      runs-on: ubuntu-latest
      steps:
        - name: Check PR Labels
          id: set_output
          run: |
            RAW_LABELS=$(echo "${{ toJSON(github.event.pull_request.labels) }}")
            for label in ${{ toJSON(github.event.pull_request.labels) }}; do
              echo $label.name
            done
            

    check-labels:
        needs: handle_label
        runs-on: ubuntu-latest
        steps:
          - name: Get Labels Output
            run: |
                echo "Labels from the labeled job: " echo output.txt
