name: (Internal) Handle PR Labels based in a commit
run-name:  (Internal) Handle PR Labels based in a commit

permissions: write-all

on:
  workflow_call:
    outputs:
      ORBITDOTNET_FOUND:
        value: ${{ jobs.get_labels_release.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND:
        value: ${{ jobs.get_labels_release.outputs.ORBITDOTNET_RESULTS_FOUND }}
        
jobs:
  get_labels_release:
    runs-on: ubuntu-latest
    outputs:
      ORBITDOTNET_FOUND: ${{ steps.get_labels_release.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND: ${{ steps.get_labels_release.outputs.ORBITDOTNET_RESULTS_FOUND }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Get PR Number
        run: |
          echo "${{github.event.before}}"
          # Use GitHub CLI to find the PR associated with the commit
          PR_NUMBER=$(gh pr list --state merged --json number,commits --jq '.[] | select(.commits[].oid == "'${{ github.sha }}'") | .number')



          echo "$PR_NUMBER"
