name: Release Candidate Workflow

on:
    pull_request: 

  
jobs:
    labeler:
      uses: ./.github/workflows/labeler.yml

    handle_label:
      uses: ./.github/workflows/teste-main.yml

    push_OrbitDotnet:
      needs: [handle_label]
      if:  ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}

    push_OrbitDotnet_Results:
      needs: [handle_label]
      if:  ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}



