name: Release Candidate Workflow

on:
    pull_request: 
        types: [closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  #Fazer a versão de PROD no próprio projeto de PROD eu dirias
  
jobs:
    handle_label:
      uses: ./.github/workflows/handle-label.yml
      with:
        labels: ${{ toJSON(github.event.pull_request.labels) }}

    push_OrbitDotnet:
      needs: [handle_label]
      if:  ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}

    push_OrbitDotnet_Results:
      needs: [handle_label]
      if:  ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}



