name: Handle PR Labels

on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
    outputs:
      ORBITDOTNET_FOUND:
        value: ${{ jobs.handle_label.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND:
        value: ${{ jobs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}

jobs:
  handle_label:
    runs-on: ubuntu-latest
    outputs:
      ORBITDOTNET_FOUND: ${{ steps.check_labels.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND: ${{ steps.check_labels.outputs.ORBITDOTNET_RESULTS_FOUND }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check PR Labels
        id: check_labels
        run: |
          labels="${{ inputs.labels }}"
          echo "Rótulos: $labels"

          if echo "$labels" | grep -q OrbitDotnet,; then
            echo "O rótulo 'OrbitDotnet' está presente."
            echo "ORBITDOTNET_FOUND=true" >> $GITHUB_OUTPUT
          else
            echo "O rótulo 'orbitdotnet' NÃO está presente."
            echo "ORBITDOTNET_FOUND=false" >> $GITHUB_OUTPUT
          fi

          if echo "$labels" | grep -q OrbitDotnet.Results,; then
            echo "O rótulo 'results' está presente."
            echo "ORBITDOTNET_RESULTS_FOUND=true" >> $GITHUB_OUTPUT
          else
            echo "O rótulo 'OrbitDotnet.Results' NÃO está presente."
            echo "ORBITDOTNET_RESULTS_FOUND=false" >> $GITHUB_OUTPUT
          fi
  
