name: Release Candidate Workflow

on:
    pull_request: 
        types: [labeled, closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  
jobs:

    handle_label:
      runs-on: ubuntu-latest
      steps:
        - name: Check PR Labels
          id: set_output
          run: |
            labels="${{ toJSON(github.event.pull_request.labels) }}"
            echo "Rótulos: $labels"

            if echo "$labels" | grep -q orbitdotnet; then
              echo "O rótulo 'orbitdotnet' está presente."
              echo "label_found=true" >> $GITHUB_ENV
            else
              echo "O rótulo 'orbitdotnet' NÃO está presente."
              echo "label_found=false" >> $GITHUB_ENV
            fi


    check-labels:
        needs: handle_label
        runs-on: ubuntu-latest
        steps:
          - name: Get Labels Output
            run: |
                echo "Labels from the labeled job: " echo output.txt
