name: Release Candidate Workflow

on:
    pull_request: 

permissions:
  contents: read
  pull-requests: write

jobs:
    
    labeler:
      permissions:
        contents: read
        pull-requests: write
      runs-on: "ubuntu-latest"

      steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

    handle_label:
      needs: [labeler]
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v2
        - name: Check PR Labels
          id: check_labels
          run: |
            labels="${{ toJSON(github.event.pull_request.labels) }}"
            echo "Rótulos: $labels"

            if echo "$labels" | grep -q OrbitDotnet,; then
              echo "O rótulo 'OrbitDotnet' está presente."
              echo "ORBITDOTNET_FOUND=true" >> $GITHUB_OUTPUT
            else
              echo "O rótulo 'orbitdotnet' NÃO está presente."
              echo "ORBITDOTNET_FOUND=false" >> $GITHUB_OUTPUT
            fi

            if echo "$labels" | grep -q OrbitDotnet.Results,; then
              echo "O rótulo 'results' está presente."
              echo "ORBITDOTNET_RESULTS_FOUND=true" >> $GITHUB_OUTPUT
            else
              echo "O rótulo 'OrbitDotnet.Results' NÃO está presente."
              echo "ORBITDOTNET_RESULTS_FOUND=false" >> $GITHUB_OUTPUT
            fi
  

    push_OrbitDotnet:
      needs: [handle_label]
      if:  ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}

    push_OrbitDotnet_Results:
      needs: [handle_label]
      if:  ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}



