name: Release Candidate Workflow

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  
jobs:

    labeled:
        uses: ./.github/workflows/labeler.yml

    check-labels:
        needs: [labeled]
        uses: ./.github/workflows/test_labels.yml
