name: Release Candidate Workflow

on:
    pull_request: 
        types: [labeled, closed]

permissions:
  contents: read
  pull-requests: write  # Adicione a permissão necessária aqui

  #Fazer a versão de PROD no próprio projeto de PROD eu dirias
  
jobs:
    handle_label:
      uses: ./.github/workflows/handle-label.yml
      with:
        labels: ${{ toJSON(github.event.pull_request.labels) }}

    build:
      uses: peob/pmp-workflows/.github/workflows/build_dotnet.yml@main
      secrets: inherit

    sonar-analysis:
      uses: peob/pmp-workflows/.github/workflows/sonar_analysis.yml@main
      with:
        INTEGRATIONS_TESTS: false
      secrets: inherit

    codeql:
      uses: peob/pmp-workflows/.github/workflows/codeql.yml@main
      secrets: inherit

    push_OrbitDotnet:
      needs: [handle_label, sonar-analysis, codeql]
      if:  ${{ needs.call_handle_label.outputs.ORBITDOTNET_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.call_handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.call_handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}

    push_OrbitDotnet_Results:
      needs: [handle_label, sonar-analysis, codeql]
      if:  ${{ needs.call_handle_label.outputs.ORBITDOTNET_RESULTS_FOUND == 'true' }}
      uses: ./.github/workflows/pack_and_push.yml
      with: 
        ORBITDOTNET_FOUND: ${{ needs.call_handle_label.outputs.ORBITDOTNET_FOUND }}
        ORBITDOTNET_RESULTS_FOUND: ${{ needs.call_handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}



