name: "(internal) Pull Request Labeler"
run-name: "(internal) Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait for Labels to be Applied
      run: sleep 5  # Aguarda 5 segundos
        
    - name: Execute Step if Label Present
      if: contains(github.event.pull_request.labels.*.name, 'orbitdotnetresult')
      run: echo "The PR has the specific label!"