name: "(internal) Pull Request Labeler"
run-name: "(internal) Pull Request Labeler"
#on:
#- pull_request_target

on:
    pull_request:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Output for Labels
      id: set_output
      run: |
        echo "labels=$(echo '${{ toJSON(github.event.pull_request.labels) }}')" >> $GITHUB_OUTPUT
