name: "(internal) Pull Request Labeler"
run-name: "(internal) Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait for Labels to be Applied
      run: sleep 5  # Aguarda 5 segundos
        
    - name: Check Labels
      run: |
        echo "Labels on the PR:"
        for label in "${{ toJson(github.event.pull_request.labels) }}"; do
        echo "${label.name}"
        done