name: "(internal) Pull Request Labeler"
run-name: "(internal) Pull Request Labeler"

on:
  pull_request:
    
jobs:
  labeler:
    permissions:
      contents: write
      pull-requests: write
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: 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
