name: "(internal) Pull Request Labeler"
run-name: "(internal) Pull Request Labeler"
#on:
#- pull_request_target

on:
    workflow_call:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
