name: Pack and Push
run-name: Pack and Push

on:
    workflow_call:
        inputs:
            ORBITDOTNET_FOUND:
                required: false
                type: string
            ORBITDOTNET_RESULTS_FOUND:
                required: false
                type: string

jobs:

    orbit:
        runs-on: ubuntu-latest
        steps:
            - name: Setup .NET
              if: ${{ inputs.ORBITDOTNET_FOUND == 'true' }}
              run: |
                echo "OrbitDotnet Found"

            - name: Setup .NET
              if: ${{ inputs.ORBITDOTNET_RESULTS_FOUND == 'true' }}
              run: |
                echo "Results Found"