name: Pack and Push

on:
    workflow_call:
        inputs:
            ORBITDOTNET_FOUND:
                required: false
                type: string
            RESULTS_FOUND:
                required: false
                type: string

jobs:

    orbit:
        runs-on: cawe-linux-x64-compute-medium
        steps:
            - name: Setup .NET
              if: ${{ inputs.ORBITDOTNET_FOUND == 'true' }}
              run: |
                echo "OrbitDotnet Found"

            - name: Setup .NET
              if: ${{ inputs.RESULTS_FOUND == 'true' }}
              run: |
                echo "Results Found"