name: Release Workflow

on:
  push: 
    branches:
      - master

permissions: write-all
      
jobs:

  handle_label: 
    uses: ./.github/workflows/handle-label-release.yml

  build:
    needs: [handle_label]
    if: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND == 'true' || needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND == 'true' }}
    uses: ./.github/workflows/pack_and_push.yml
    secrets: inherit
          
  push_OrbitDotnet_Results:
    needs: [handle_label]
    if: ${{needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND == 'true' }}
    uses: ./.github/workflows/pack_and_push.yml
    with:
      ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}
    secrets: inherit

  push_OrbitDotnet:
    needs: [handle_label]
    if: ${{needs.handle_label.outputs.ORBITDOTNET_FOUND == 'true' }}
    uses: ./.github/workflows/pack_and_push.yml
    with:
      ORBITDOTNET_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_FOUND }}
      ORBITDOTNET_RESULTS_FOUND: ${{ needs.handle_label.outputs.ORBITDOTNET_RESULTS_FOUND }}
    secrets: inherit