name: Deploy Dev Teste

on:
  push: 
    branches:
      - master

permissions: write-all
      
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Image number
        run: |
          OFFSET=64
          TAG_NUMBER=$(( GITHUB_RUN_NUMBER + OFFSET ))
          echo "TAG_NUMBER=$TAG_NUMBER" >> $GITHUB_ENV

      - name: Build and Push Docker Images for Each App
        run: |
          echo "${{ env.TAG_NUMBER }}"
