name: Teste Main

on:
    push: 
        branches:
        - master

        
jobs:
  get_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get the latest PR merged into main
        id: get_pr
        run: |
          # Obter o commit SHA do push
          commit_sha="${{ github.sha }}"
          
          # Usar a API do GitHub para encontrar o PR associado ao commit
          pr_url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${commit_sha}/pulls" | jq -r '.[0].url')

          if [ "$pr_url" != "null" ]; then
            echo "PR URL: $pr_url"
            # Obter as labels do PR
            labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$pr_url" | jq -r '.labels[].name')
            echo "Labels do PR:"
            echo "$labels" | tr '\n' ',' | sed 's/,$//'
            echo "LABELS=$labels" >> $GITHUB_ENV
          else
            echo "Nenhum PR associado a este commit."
          fi
