on:
    pull_request: 
        types: [labeled, closed]

jobs:
  handle_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        run: |
          echo "Labels on the PR:"
          echo "${{ toJSON(github.event.pull_request.labels.*.name) }}"

