name: Reusable Workflow

on:
  workflow_call:
    inputs:
      api-key:
        description: 'API Key'
        required: true
        type: string
    secrets:
      API_KEY:
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print API Key
        run: | 
          echo "API Key: ${{ secrets.API_KEY }}"
