on:
    workflow_call: 

jobs:
  handle_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        id: set_output
        run: |
          raw_labels="${{ toJSON(github.event.pull_request.labels) }}"
          echo "Raw PR labels: $raw_labels"
          
          # Extrair os valores da propriedade name
          names=$(echo "$raw_labels" | sed -n 's/.*"name": "\(.*\)".*/\1/p')
          
          # Verificar se foram encontrados nomes
          if [ -z "$names" ]; then
            echo "No labels found"
            echo "labels=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Armazenar os nomes no formato desejado
          echo "labels=[$(echo "$names" | tr '\n' ',' | sed 's/,$//')]" >> $GITHUB_OUTPUT


          