on:
    workflow_call:

jobs:
  handle_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        run: |
          echo "Labels on the PR:"
          for label in "${{ toJson(github.event.pull_request.labels) }}"; do
            echo "${label.name}"
          done

