on:
    workflow_call: 

jobs:
  handle_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        id: set_output
        run: |
          labels=$(echo '${{ toJSON(github.event.pull_request.labels) }}')
          echo "labels=$labels" >> $GITHUB_OUTPUT
