on:
    workflow_call: 

jobs:
  handle_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        run: |
          echo "Labels on the PR:"
          labels=$(echo "${{ toJSON(github.event.pull_request.labels.*.name) }}")
          echo "labels=$labels" >> $GITHUB_OUTPUT  # Armazenar as labels no output

